manifest:
  remotes:
    # zmk official
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: dabase_v1-1
      url-base: https://github.com/dabase_v1-1

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: dabase_v1-1
      remote: dabase_v1-1
      revision: main

self:
  path: config
